name: CI
on:
  push:
    branches:
      - master
    tags: ['*']

jobs:
  REPLTestsCommons:
    name: Sequential-Commons
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.11.1'
          arch: x64
      - uses: actions/cache@v4
        with:
          path: ~/.julia/artifacts
          key: ubuntu-test-cache-${{ hashFiles('**/Project.toml') }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-sequential-commons
          path: ./coverage-sequential-commons.info

  REPLTestsCases:
    name: Sequential-Cases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.11.1'
          arch: x64
      - uses: actions/cache@v4
        with:
          path: ~/.julia/artifacts
          key: ubuntu-test-cache-${{ hashFiles('**/Project.toml') }}
      - uses: julia-actions/julia-buildpkg@v1
      - run: julia --project=. -e "include(joinpath(\"test\", \"sequential\", \"runtests.jl\"))"
      - uses: julia-actions/julia-processcoverage@v1
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-sequential-cases
          path: ./coverage-sequential-cases.info

  UtilsTests:
    name: Sequential-Utils
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.11.1'
          arch: x64
      - uses: actions/cache@v4
        with:
          path: ~/.julia/artifacts
          key: ubuntu-test-cache-${{ hashFiles('**/Project.toml') }}
      - uses: julia-actions/julia-buildpkg@v1
      - run: julia --project=. -e "include(joinpath(\"test\", \"UtilsTests\", \"runtests.jl\"))"
      - uses: julia-actions/julia-processcoverage@v1
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-sequential-utils
          path: ./coverage-sequential-utils.info

  MPITests:
    name: SegregatedVMSSolver-MPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.11.1'
          arch: x64
      - uses: actions/cache@v4
        with:
          path: ~/.julia/artifacts
          key: ubuntu-mpi-test-cache-${{ hashFiles('**/Project.toml') }}
      - uses: julia-actions/julia-buildpkg@v1
      - run: julia --project=. -e "include(joinpath(\"test\", \"mpi\", \"runtests.jl\"))"

  mergeCoverage:
    name: Merge Coverage & Upload
    runs-on: ubuntu-latest
    needs: [REPLTestsCommons, REPLTestsCases, UtilsTests]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          path: coverage_reports
      - run: |
          using Pkg
          Pkg.activate(temp=true)
          Pkg.add("Coverage")
          using Coverage
          coverage = LCOV.readfolder(".")
          for cov in coverage
            cov.filename = replace(cov.filename, "\\" => "/")
          end
          coverage = merge_coverage_counts(coverage)
          @show covered_lines, total_lines = get_summary(coverage)
          LCOV.writefile("./lcov.info", coverage)
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info
